Minor
vldF/compoly pull request #44
Opened 2022-06-13 18:35 UTC by vldF

Fix virtualtargets in respect/disrespect commands 
Add notification for Gulag and Mute are ended up

2022-06-13 22:53 UTC, donebd requested changes

2022-06-13 22:53 UTC, donebd commented on src/main/kotlin/chatbot/chatModules/voting/Gulag.kt
> +        val targetId = targetMention.targetId ?: error("target id is null for mention $targetMention")
Почему здесь мы не уверены что targetId не null, а в муте и реварде уверены?)

2022-06-13 22:53 UTC, donebd commented on src/main/kotlin/chatbot/chatModules/voting/Reward.kt
> +        val targetId = targetMention.targetId!!
Тут мы уверены

2022-06-13 22:53 UTC, donebd commented on src/main/kotlin/chatbot/chatModules/voting/Votable.kt
> +        dynamicRunTimeMillis: AtomicLong,
хорошее исправление, что время вызова, а не делей)) я сам себя запутал))

2022-06-13 22:53 UTC, donebd commented on src/main/kotlin/chatbot/chatModules/voting/Mute.kt
> +        val targetId = targetMention.targetId!!
тут мы уверены

2022-06-13 22:53 UTC, donebd commented on src/main/kotlin/chatbot/chatModules/voting/Votable.kt
> +    protected fun sendDelayedMessage(
Неочевидный нейминг (т.к. у нас в VkApi.send() можно передать задержку или динамическое время удаления) и еще тут по дефолту тоже получается динамическое время удаление, что может чисто в теории привести к веселым ситуациям (хотя AtomicLong довольно ясно дает понять что время не статическое)

2022-06-13 22:53 UTC, donebd commented on src/main/kotlin/chatbot/chatModules/voting/Gulag.kt
> +    private val kickDuration = Duration.ofHours(12) // Время нахождения в ГУЛАГе
Давай тогда и в самом votable заменим timeOfClosing с помощью Duration

2022-06-14 09:36 UTC, donebd commented
Еще кста если тесты выпиливаешь, надо из README тоже выпилить

2022-06-25 10:34 UTC, vldF commented on src/main/kotlin/chatbot/chatModules/voting/Gulag.kt
> +        val targetId = targetMention.targetId ?: error("target id is null for mention $targetMention")
Да на самом деле, мы везде одинаково уверены. Просто тут я почему-то сделал более адекватный вывод ошибки

2022-06-25 10:39 UTC, vldF commented on src/main/kotlin/chatbot/chatModules/voting/Mute.kt
> +        val targetId = targetMention.targetId!!
Мы не можем быть уверены в этом, так как у нас нет никаких контрактов -- эта проперти в классе Mention отмечена как nullable. Конкретно сейчас (я посмотрел) у нас везде есть проверка на то, что если targetId == null, то мы отправляем сообщение с ошибкой, но при этом в какой-то момент мы можем что-то поменять (даже нечаянно) и придётся смотреть и разбираться, в каком из меншенов null всё-таки просочился. По этому лучше всего использовать не !!, а error(), там можно сделать чуть более детальный вывод сообщения с ошибкой

2022-06-26 09:41 UTC, merged